server {
    listen 80 default_server;
    server_name zenod.dev _;
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name ring.zenod.dev;
    root /usr/share/nginx/html;

    location = / {
        try_files /ring/index.html =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
